services:
  - node:latest

stages:
  - deploy

before_script:
  - yarn config set registry https://registry.npm.taobao.org
  - yarn install

work_job:
  stage: deploy
  tags:
    - node-runner
  only:
    - tags
  script:
    - npm run test
    - npm run build
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm publish
